### PR TITLE
Initial Translations Support - Fixes #232

### LINKED ISSUE #232: Add translations support

### PR DESCRIPTION
**Pull request by Technoblazed**
Things are about to magically appear! >:D

💀  

- [X] shavit-core
- [X] shavit-chat
- [x] shavit-hud
- [X] shavit-misc
- [X] shavit-rankings
- [X] shavit-readme
- [X] shavit-replay
- [X] ~~shavit-sounds~~
- [X] ~~shavit-timelimit~~
- [X] shavit-stats
- [X] shavit-wr
- [X] shavit-zones

EDIT: I literally wanna kms right now, I hope you guys are happy.
EDIT: FUCK YOU GABEN.

### CODE REVIEW

**Comment by shavitush** [comment]
If possible, use `%T` instead of `%t` and pass `client` as an argument, so the client gets the translation in his own language!

**Comment by Nickelony** [comment]
https://puu.sh/s4okP.png
^ Can you add an option to translate this too?

In this case: (just an example)
Czas: 0.0 (1)          Najlepszy: 19.562 (#6)
Skoki: 0                 Styl: Normal
Prędkość: 249       Strefy: 0 (0.00%)

**Comment by Technoblazed** [comment]
@Nickelony I guess? Might look weird with larger names though.

**Comment by Nickelony** [comment]
@Technoblazed We'll see :>

**Comment by Technoblazed** [comment]
I've given up today, I'll finish the rest off tomorrow

**Comment by Technoblazed** [comment]
@Nickelony will that do?

**Comment by Nickelony** [comment]
@Technoblazed Yup, it's perfect :)

**Comment by Technoblazed** [comment]
Rest of the items will be pushed soon, WR module is aids. Zones module is aids. Stats soon :tm:

**Comment by Technoblazed** [comment]
ONE MORE

**Comment by Technoblazed** [comment]
-Done-

**Comment by shavitush** [comment]
Amazing contribution, thank you!

**Pull request merged**
