### PR TITLE
zones wip

### PR DESCRIPTION
**Pull request by rtldg**
stuff
- `Shavit_AddZone`
  - for adding zones via thirdparty plugin
- `Shavit_RemoveZone`
- `Shavit_UnloadZones`
- `Shavit_ReloadZones`
- `Shavit_LoadZonesHere`
- `Shavit_ParseZoneTargetname`
- removed `Shavit_GetStageZone`
- other zone natives...
- hooking `trigger_multiple`s
- adds `shavit-zones-http.sp`
- increased `MAX_ZONES` to `128`
- increased `MAX_STAGES` to `69`
- `ZoneForm_*`
- menus

todo
- ~~figure out what to do about prebuilt zones~~ ---- **done ish**
- ~~add the prebuilt zone targetname migrator thing~~ --- meh
- ~~Area&Cluster stuff for stages (/ any type of zone?)~~ for another time

### CODE REVIEW

**Comment by Ciallo-Ani** [comment]
Is it feasible to add `hammerid` to prevent repeated naming triggers conflicts?

**Comment by rtldg** [comment]
> Is it feasible to add `hammerid` to prevent repeated naming triggers conflicts?

Haven't looked at the base commit in a month, but it seems like I intended for `sTarget` to hold the `hammerid` or `targetname`. I think I forgot to add a `ZF_` flag for the `hammerid` though

**Comment by rtldg** [comment]
> at this point bhop map authors are smarter than surf, i cant stand them whatever

hahaha, and bhop map authors still make a lot of mistakes

**Comment by rtldg** [comment]
I think everything is working. Didn't do the area&cluster stuff (yet:tm:). Still want to remove the `#if` preprocessor stuff from `shavit-zones-http.sp` and have a convar to switch between steamworks or ripext. Will do that later though

**Pull request merged**
