### PR TITLE
fix replay bots getting stuck

### PR DESCRIPTION
**Pull request by PaxPlay**
Fixed Replay Bots getting stuck by teeleporting the bot every _ReplayCheckFrame_ frames.

### CODE REVIEW

**Comment by PaxPlay** [comment]
Replay bots get laggy...

**Comment by Zipcore** [comment]
if((gI_ReplayTick[iReplayBotStyle] % 128) == 0 && SquareRoot(Pow(vecVelocity[0], 2.0) + Pow(vecVelocity[1], 2.0)) < 2.0*Entity_GetDistanceOrigin(client, vecPosition))
		TeleportEntity(client, vecPosition, vecAngles, vecVelocity);
	else TeleportEntity(client, NULL_VECTOR, vecAngles, vecVelocity);

	stock float Entity_GetDistanceOrigin(int entity, const float vec[3])
	{
		float entityVec[3];
		GetEntPropVector(entity, Prop_Send, "m_vecOrigin", entityVec);
	
		return GetVectorDistance(entityVec, vec);
	}

**Comment by Zipcore** [comment]
I've added support for high speed aswell, enjoy

**Comment by shavitush** [comment]
might want to change 128 to `gF_Tickrate`

**Comment by Zipcore** [comment]
Not really it doesn't have to be set to the tickrate. You could check everytime too so the bot can't get stuck for 1s or more.

**Comment by Nickelony** [comment]
I would apply zipcore's fix tbh

**Comment by shavitush** [comment]
I forgot about it! Will do today.

**Comment by SlidyBat** [comment]
Does everything need to be square rooted? Bit expensive for OnPlayerRunCmd

**Comment by shavitush** [comment]
My implementation doesn't do that. I use [GetVectorLength\(\)](https://github.com/alliedmodders/sourcemod/blob/237db0504c7a59e394828446af3e8ca3d53ef647/core/smn_vector.cpp#L45-L59) instead.

**Comment by SlidyBat** [comment]
Both GetVectorLength and GetVectorDistance still square root by default, theres an optional parameter to leave them squared: https://sm.alliedmods.net/new-api/vector/GetVectorLength , https://sm.alliedmods.net/new-api/vector/GetVectorDistance

I think when just comparing, youre better off leaving squared

**Pull request closed without merging**
