### PR TITLE
Fix broken advertisements, add shavit_zones_teleporttoend

### PR DESCRIPTION
**Pull request by shavitush**
Solves (#271) and (#270)

### CODE REVIEW

**Comment by Nickelony** [comment]
The zone colors are still wrong. It's like you didn't fix anything.

**Comment by Nickelony** [comment]
The first advertisement appeared after 10 minutes. I think it's ignoring the cvar completely.

**Comment by shavitush** [comment]
@Nickelony reverted the change then, I'll solve it within the rewrite of the zones plugin because atm it's super messy :(.

**Comment by shavitush** [comment]
@Nickelony fixed the issue you had

**Comment by Nickelony** [comment]
I'm gonna test it in a few hours :)

**Comment by Nickelony** [comment]
Sorry but the advertisements are still glitched. They appear randomly without any order.

**Comment by shavitush** [comment]
can you record it with the interval set to something like 5 so i can see what exactly happens? also provide the advertisement config file

**Comment by Nickelony** [comment]
Video: https://www.youtube.com/watch?v=qvWcHsEJo_4
Config files: https://puu.sh/rV8Nx.zip
Changing the cvar to another value didn't change anything. :/

**Comment by Technoblazed** [comment]
Cvars like that shouldnt really be changed in the middle of rounds.

**Comment by Nickelony** [comment]
It was set to 10 by default and I was changing the map to see if something would change.

**Comment by Technoblazed** [comment]
So I take it you edited the value of the cvar in the config file, then changed maps correct?

**Comment by Nickelony** [comment]
Yes.

**Comment by Nickelony** [comment]
I've tested it again with 6 players and the ad appeared at 12:36

**Comment by Technoblazed** [comment]
@Nickelony to confirm, you restarted your server, not changed maps correct?

**Comment by Nickelony** [comment]
Yes, I've also tried to restart the server and it didn't help.

**Comment by shavitush** [comment]
done testing with these, report asap if they don't work

**Comment by Nickelony** [comment]
They are still broken and the update didn't change anything.

**Comment by shavitush** [comment]
i'm horribly sorry but i can't replicate your issue at all

**Comment by Nickelony** [comment]
I tried to re-install the server and nothing changed. I'm using the lastest sm 1.8 and the advertisements only freak out when there are other players on the server.

**Comment by shavitush** [comment]
does it just spam advertisements?

**Comment by Technoblazed** [comment]
Tested with 10 players and can't repeat

**Comment by Nickelony** [comment]
as shown in the video, they appear randomly in a random order and I have no idea why ._.

my plugin list:
```
[SM] Listing 39 plugins:
01 "[shavit] Sounds" (1.5b) by shavit
02 "Basic Votes" (1.8.0.5947) by AlliedModders LLC
03 "Basic Chat" (1.8.0.5947) by AlliedModders LLC
04 "Basic Comm Control" (1.8.0.5947) by AlliedModders LLC
05 "Chat-Processor" (1.1.2) by Keith Warren (Drixevel)
06 "CrazySpeed" (1.0.2) by Soccerdude
07 "Basic Ban Commands" (1.8.0.5947) by AlliedModders LLC
08 "Reserved Slots" (1.8.0.5947) by AlliedModders LLC
09 "Sound Commands" (1.8.0.5947) by AlliedModders LLC
10 "Admin Menu" (1.8.0.5947) by AlliedModders LLC
11 "invis.smx"
12 "[shavit] Miscellaneous" (1.5b) by shavit
13 "Dynamic" (0.0.22) by Neuro Toxin
14 "[shavit] Core" (1.5b) by shavit
15 "Fun Commands" (1.8.0.5947) by AlliedModders LLC
16 "Anti-Flood" (1.8.0.5947) by AlliedModders LLC
17 "[shavit] HUD" (1.5b) by shavit
18 "Basic Commands" (1.8.0.5947) by AlliedModders LLC
19 "Admin File Reader" (1.8.0.5947) by AlliedModders LLC
20 "[shavit] Player Stats" (1.5b) by shavit
21 "[shavit] World Records" (1.5b) by shavit
22 "[shavit] Replay Bot" (1.5b) by shavit
23 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
24 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
25 "Slope Landing Fix" (1.2) by Mev & Blacky
26 "Force Map End" (1.1) by Zipcore, 1NutWunDeR
27 "Client Preferences" (1.8.0.5947) by AlliedModders LLC
28 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
29 "Nextmap" (1.8.0.5947) by AlliedModders LLC
30 "Trigger_Push Fix" (1.2) by iEx
31 "No blood" (0.1.0) by H3bus
32 "Basic Info Triggers" (1.8.0.5947) by AlliedModders LLC
33 "[shavit] Rankings" (1.5b) by shavit
34 "Admin Help" (1.8.0.5947) by AlliedModders LLC
35 "Fun Votes" (1.8.0.5947) by AlliedModders LLC
36 "[shavit] Map Zones" (1.5b) by shavit
37 "[shavit] Chat" (1.5b) by shavit
38 "No Weapon Fix" (1.3.1) by .#Zipcore
39 "Player Commands" (1.8.0.5947) by AlliedModders LLC
```

**Comment by shavitush** [comment]
just know that the cvar only takes effect after you restart the server

**Comment by Nickelony** [comment]
I know. 
I was restarting the server.
Nothing changed.

**Pull request merged**
