### PR TITLE
Don't force clients to download in-game sounds

### PR DESCRIPTION
**Pull request by strafe**

### CODE REVIEW

**Comment by Nairdaa** [comment]
Edit https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/configs/shavit-sounds.cfg file...

**Comment by strafe** [comment]
> Edit https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/configs/shavit-sounds.cfg file...

What?

I'm going to close this because as Slidy pointed out some people might not keep the sound file(s) on the server itself and only on fastdl. I'm guessing the only way to go about this (assuming there isn't a way to determine if a sound is custom or not programatically) is to add more logic to the sounds config and let users explicitly mark sounds as custom (or not custom with backwards compatibility in mind).

**Comment by Nairdaa** [comment]
There are only custom sounds to download in the downloadables table. If people don't have the default sounds (wich is in their game package since the pipe update, instead of the default /sounds folder), connecting to a server won't force them to download them, it will instead print a console error while trying to play one.

**Comment by Nairdaa** [comment]
Not to mention you missed the {} in the if statement.

**Comment by sneak-it** [comment]
{} is not required.

**Comment by Nairdaa** [comment]
Yes, I'm now completely aware of that now after Adam educated me in a discussion we've had on the official timer's Discord.

**Pull request closed without merging**
