### PR TITLE
Teleport to end

### PR DESCRIPTION
**Pull request by OfficialExtan**

### CODE REVIEW

**Comment by Technoblazed** [comment]
Double pull?

**Comment by OfficialExtan** [comment]
I really dont know how to do this dude. I'm very new to this.

**Comment by Technoblazed** [comment]
Are you trying to add your new code to shavit-zones.sp ?

**Comment by shavitush** [comment]
Add both commits to the patch-1 branch and send the pullrequest again

I'll check it when I get home!

**Comment by OfficialExtan** [comment]
yes im trying to add the changes from shavit-core.sp to the pullrequest of the shavit-zones.sp

**Comment by Technoblazed** [comment]
Added you on steam

**Pull request closed without merging**
