### PR TITLE
Rankings rewrite

### LINKED ISSUE #465: Rankings plugin rewrite
This will be the issue to track the rewrite of rankings.

The following is the design idea I wrote, and I just started working on the implementation itself:
> Design idea:
> 
> Rank 1 per map/style/track gets ((points per tier * tier) * 1.5) + ((amount of records * (tier / 10.0) * 0.25)) + (rank 1 time in seconds / 15.0) points.
> Records below rank 1 get points% relative to their time in comparison to rank 1 and a final multiplier of 0.85% to promote rank 1 hunting.
> 
> Bonus track gets a 0.25* final mutliplier for points and is treated as tier 1.
> 
> Points for all styles are combined to promote competitive and fair gameplay.
> A player that gets good times at all styles should be ranked high.
> 
> Total player points are weighted in the following way: (descending sort of points)
> points[0] * 0.975^0 + points[1] * 0.975^1 + points[2] * 0.975^2 + ... + points[n] * 0.975^(n-1)
> 
> The ranking leaderboard will be calculated upon: map start.
> Points are calculated per-player upon: connection/map.
> Points are calculated per-map upon: map start, map end, tier changes, world record (for track/style).
> Rankings leaderboard is re-calculated once per map change.
> A command will be supplied to recalculate all of the above.
> 
> Heavily inspired by pp (performance points) from osu!, written by Tom94. https://github.com/ppy/osu-performance

### PR DESCRIPTION
**Pull request by shavitush**
Fixes #465.

Note: This version of rankings doesn't support SQLite, I'm sorry but I can't wrap my head around getting `UpdateAllPoints`, `UpdatePlayerPoints` and `RecalculateMap` to work on SQLite. If you can do it, please send a pull request or post a patch here.

Differences:
* This one is much MUCH MUCH faster.
* Less database interaction.
* No chat ranks here. They'll be re-added into `shavit-chat` after release. I don't have too much time for that right now unfortunately..
* More caching. Your database won't die when people spam `sm_top`.
* Points are calculated by tier.
* Fixed SQL injection (thanks eXtaZy).
* Removed `Shavit_OnRankUpdated` because it has no real use.

Extras:
* Fixed `{rand}` in CS:GO chat processing.
* Fixed back buttons in !replay.
* Made zone calculation faster.
* Remade key display! Now it'll be aesthetic for both CS:S and CS:GO. It'll also show players holding the JUMP button while on auto. Added it so players can help others that don't realize autobhop is on and instead keep scrolling. It's also decent to see if someone is cheating like that. I've also made it insta-update on key changes.
* Fixed `weapon_glock` ammo not refilling.
* Optimizing the whole database structure with indexes.

To-do before merging:
- [x] Add indexes where possible, redo column types. The index changes can't be nicely added, so I'll try my best to add documentation for how to manually add them when this is done! The changes will apply to newly created tables.
- [x] Fix an issue where !rank may show points of another player.
- [x] Fix an issue where times will sometimes not have points calculated.
- [x] Fix shavit-stats not taking tracks into consideration. Also do descending point sorting.
- [x] Fix `[shavit-rankings.smx] Transaction query (0): Column 'points' cannot be null`.
- [x] Fix WR menu showing rank 1/0 for bonus track.
- [x] Do a migration to both database/plugins so `workshop/` will never show in map names.
- [x] Fix WR menu showing the map's *id* instead of the map's name when using !wr <map> for workshop maps.
- [x] Remove head tilting in shavit-misc, when hiding.
- [x] Create the top 100 menu once, instead of many times.
- [x] Fix an issue where rankings only works properly when late-loaded.
- [x] Redo `Shavit_GetDB` (make it `Shavit_GetDatabase`).
- [x] Disallow `sm_stats` from opening before the menu is fully loaded.

To be done sometime:
* Store authentication IDs for users as numbers (`GetSteamAccountID`?) rather than the current SteamID. This will allow faster indexes and database I/O.
* #491, #472
* Add chat tags for ranks. (!chatrank)

After installing, set the map's tier with `sm_settier` and then run `sm_recalcall` (ROOT command) once to apply all the points retroactively. When you add new tiers for maps, the points for them will adjust accordingly.

I've tested this in a rather small server (10 users in the database) and everything was fine. Let me know if there are any issues. I'll merge when I'm done with implementing the last to-dos if there are no issues reported.

### CODE REVIEW

**Comment by strafe** [comment]
Is there a default tier, if so is it set through a cvar? If not are maps just unranked by default or not playable?

**Comment by shavitush** [comment]
@strafe the default tier is 1. I decided to make the default tier 1 instead of anything higher because maps like bhop_freedompuppies are often forgotten and will award lots of points. Players will usually not report such issues to server admins as they benefit from the map being tiered high.

**Comment by Lime18** [comment]
[shavit-rankings.smx] Transaction query (0): Column 'points' cannot be null
[shavit-rankings.smx] Timer (rankings, update player points) error! Reason: Column
rank
The accrual of points does not work :(

**Comment by shavitush** [comment]
@Lime18 can you check if it's solved now?

**Comment by Lime18** [comment]
@shavitush Does not work :(
rank5
rank3
rank4
Ranking DEBUG:
L 08/15/2017 - 15:48:48: [shavit-rankings.smx] start: 294.669494
L 08/15/2017 - 15:48:48: [shavit-rankings.smx] start: 294.681060
L 08/15/2017 - 15:48:48: [shavit-rankings.smx] end (success): 294.778747
L 08/15/2017 - 15:48:53: [shavit-rankings.smx] start: 299.481811
L 08/15/2017 - 15:48:53: [shavit-rankings.smx] start: 299.530334
L 08/15/2017 - 15:48:53: [shavit-rankings.smx] end (success): 299.622558
L 08/15/2017 - 15:48:54: [shavit-rankings.smx] start: 300.067810
L 08/15/2017 - 15:48:54: [shavit-rankings.smx] start: 300.076873
L 08/15/2017 - 15:48:54: [shavit-rankings.smx] end (success): 300.169311
L 08/15/2017 - 15:48:54: [shavit-rankings.smx] start: 300.427673
L 08/15/2017 - 15:48:54: [shavit-rankings.smx] start: 300.441772
L 08/15/2017 - 15:48:54: [shavit-rankings.smx] end (success): 300.536529
L 08/15/2017 - 15:48:54: [shavit-rankings.smx] start: 300.733764
L 08/15/2017 - 15:48:54: [shavit-rankings.smx] start: 300.743225
L 08/15/2017 - 15:48:55: [shavit-rankings.smx] end (success): 300.833770

**Comment by shavitush** [comment]
Tried setting a map tier?

**Comment by Lime18** [comment]
@shavitush yeah 
rank6

**Comment by shavitush** [comment]
@Lime18 what about the map restart?

Can you run this query and show me the resultset?

```sql
SELECT SUM(fPoints) total FROM(SELECT (points * (@f := 0.975 * @f) / 0.975) fPoints FROM playertimes t CROSS JOIN (SELECT @f := 1.0) params WHERE points > 0.0 AND auth = 'STEAMID3_HERE' ORDER BY points DESC) a;
```

Replace `STEAMID3_HERE` with your SteamID3.

**Comment by Lime18** [comment]
rank7

**Comment by shavitush** [comment]
Run `sm_recalcmap` and try again - is it solved?

**Comment by Lime18** [comment]
nope :(

**Comment by shavitush** [comment]
Can you upload (or PM me) your database? Feel free to spoof IP addresses or SteamIDs and such before.

**Comment by Lime18** [comment]
No problems.
http://dropmefiles.com/9m5yj

**Comment by shavitush** [comment]
@Lime18 Thanks! Works with your database for me now, can you confirm?

**Comment by Lime18** [comment]
@shavitush does not work :(

**Comment by shavitush** [comment]
Add this above `trans.AddQuery(sQuery);`, and send me the error logs.

```sp
LogError("(%s) %s", sAuthID, sQuery);
```

**Comment by shavitush** [comment]
Reload the map after sm_recalcmap or changing a tier. Make sure that the map has times on it. If you get logs, report back.

**Comment by Lime18** [comment]
@shavitush I really do it right, but for me it does not work...
Could you add more detailed debug to identify the problem, i no longer have any ideas :(

**Comment by shavitush** [comment]
@Lime18 this fork has the old (temporary) version of rankings that was VERY heavy in terms of database queries. If you want to add more debugging, start with `LogMessage("[debug] 1");` in `RecalculateMap` and increment.

Also, what's `sv_hibernate_when_empty` for you? Can you check if disabling it fixes the issue?

**Comment by Lime18** [comment]
Perhaps this will somehow help ...
<details>
 <summary>shavit-rankings, LogMessage</summary>

```js
void RecalculateAll(const char[] map, const int tier)
{
	for(int i = 0; i < TRACKS_SIZE; i++)
	{
		LogMessage("[debug] RecalculateAll 1"); //Logs
		for(int j = 0; j < gI_Styles; j++)
		{
			if(gA_StyleSettings[j][bUnranked])
			{
				continue;
			}

			RecalculateMap(map, i, j, tier);
			LogMessage("[debug] RecalculateAll 2"); //Logs
		}
	}
}
--------------------------------------------------------------------------------------------------------
			gS_MySQLPrefix, gS_MySQLPrefix,
			gF_PointsPerTier, (track == Track_Main)? tier:1, (track == Track_Main)? tier:1,
			gS_MySQLPrefix, gS_MySQLPrefix,
			gA_StyleSettings[style][fRankingMultiplier], (track == Track_Main)? 1.0:0.25,
			map, track, style);

	LogMessage("[debug] RecalculateMap"); //Logs
	gH_SQL.Query(SQL_Recalculate_Callback, sQuery, 0, DBPrio_High);
}
--------------------------------------------------------------------------------------------------------
void UpdateAllPoints()
{
	char[] sQuery = new char[128];
	FormatEx(sQuery, 128, "SELECT auth FROM %splayertimes WHERE points > 0.0 GROUP BY auth;", gS_MySQLPrefix);
	gH_SQL.Query(SQL_UpdateAllPoints_Callback, sQuery, 0, DBPrio_Low);
	LogMessage("[debug] UpdateAllPoints"); //Logs
}
--------------------------------------------------------------------------------------------------------
	#endif

	LogMessage("[debug] SQL_UpdateAllPoints_Callback 1"); //Logs
	
	if(results.RowCount > 0)
	{
		while(results.FetchRow())
		{
			char[] sAuthID = new char[32];
			results.FetchString(0, sAuthID, 32);

			int client = 0;

			if(auths.GetValue(sAuthID, client))
			{
				UpdatePlayerPoints(client);
				LogMessage("[debug] SQL_UpdateAllPoints_Callback 2"); //Logs

				continue;
			}
			LogMessage("[debug] SQL_UpdateAllPoints_Callback 3"); //Logs
			
			char[] sQuery = new char[512];
```
</details>
<details>
 <summary>Logs</summary>

```js
L 08/20/2017 - 14:22:07: -------- Mapchange to workshop/738773708/bhop_skylook2 --------
L 08/20/2017 - 14:22:08: [shavit-rankings.smx] [debug] RecalculateAll 1
L 08/20/2017 - 14:22:08: [shavit-rankings.smx] [debug] RecalculateAll 1
L 08/20/2017 - 14:22:08: [shavit-rankings.smx] [debug] UpdateAllPoints
L 08/20/2017 - 14:22:09: [shavit-rankings.smx] [debug] SQL_UpdateAllPoints_Callback 1
```
</details>
--------------------------------------------------------------------------------------------------------
<details>
 <summary>shavit-rankings 2</summary>

```js
void RecalculateAll(const char[] map, const int tier)
{
	for(int i = 0; i < TRACKS_SIZE; i++)
	{
		LogMessage("[debug] RecalculateAll 1"); //Logs
		//for(int j = 0; j < gI_Styles; j++)
		//{
			int j = 0;
			if(gA_StyleSettings[j][bUnranked])
			{
				continue;
			}

			RecalculateMap(map, i, j, tier);
			LogMessage("[debug] RecalculateAll 2"); //Logs
		//}
	}
}
------------------ Change ">" to ">=" ------------------
void UpdateAllPoints()
{
	char[] sQuery = new char[128];
	FormatEx(sQuery, 128, "SELECT auth FROM %splayertimes WHERE points >= 0.0 GROUP BY auth;", gS_MySQLPrefix); //Change ">" to ">="
	gH_SQL.Query(SQL_UpdateAllPoints_Callback, sQuery, 0, DBPrio_Low);
	LogMessage("[debug] UpdateAllPoints"); //Logs
}
```
</details>

<details>
 <summary>Logs</summary>

```js
L 08/20/2017 - 14:25:25: -------- Mapchange to workshop/738773708/bhop_skylook2 --------
L 08/20/2017 - 14:25:26: [shavit-rankings.smx] [debug] RecalculateAll 1
L 08/20/2017 - 14:25:26: [shavit-rankings.smx] [debug] RecalculateMap
L 08/20/2017 - 14:25:26: [shavit-rankings.smx] [debug] RecalculateAll 2
L 08/20/2017 - 14:25:26: [shavit-rankings.smx] [debug] RecalculateAll 1
L 08/20/2017 - 14:25:26: [shavit-rankings.smx] [debug] RecalculateMap
L 08/20/2017 - 14:25:26: [shavit-rankings.smx] [debug] RecalculateAll 2
L 08/20/2017 - 14:25:26: [shavit-rankings.smx] [debug] UpdateAllPoints
L 08/20/2017 - 14:25:27: [shavit-rankings.smx] [debug] SQL_UpdateAllPoints_Callback 1
L 08/20/2017 - 14:25:27: [shavit-rankings.smx] [debug] SQL_UpdateAllPoints_Callback 3
```
</details>
<details>
 <summary>Error</summary>

```js
L 08/20/2017 - 14:25:27: SourceMod error session started
L 08/20/2017 - 14:25:27: Info (map "workshop/738773708/bhop_skylook2") (file "errors_20170820.log")
L 08/20/2017 - 14:25:27: [shavit-rankings.smx] ([U:1:172470771]) UPDATE users u JOIN (SELECT SUM((points * (@f := 0.975 * @f) / 0.975)) total FROM playertimes t CROSS JOIN (SELECT @f := 1.0) params WHERE points > 0.0 AND auth = '[U:1:172470771]' ORDER BY points DESC) temp SET u.points = temp.total WHERE auth = '[U:1:172470771]';
L 08/20/2017 - 14:25:27: [shavit-rankings.smx] Transaction query (0): Column 'points' cannot be null
```
</details>

**Comment by shavitush** [comment]
@Lime18 what about reloading shavit-rankings while the server is up, does it fix the issue for you?

**Comment by Lime18** [comment]
@shavitush LOL, it really works :) `sm_rcon sm plugins reload shavit-rankings`
Thanks!

**Comment by shavitush** [comment]
Thanks @Lime18! I'll investigate it further.

**Comment by shavitush** [comment]
@Lime18 my apologies for taking 18 days to investigate, but it should work now! :)
Let me know if there are any issues.

**Comment by Lime18** [comment]
@shavitush It works, thanks :)

**Comment by Lime18** [comment]
Could you add a team for scoring points all the maps? It's not very convenient to use sm_recalcmap on every map, when the maps are more than 200 :(
Or something simple, like sm_recalcmap mapname "sm_recalcmap bhop_lego2"

**Comment by shavitush** [comment]
@Lime18 will do!

**Comment by shavitush** [comment]
@Lime18 `sm_recalcall` is the new command to calculate all points.

**Comment by Lime18** [comment]
@shavitush Thank you so much :)

**Comment by shavitush** [comment]
Just wrote this for MySQL/MariaDB: this is a stored procedure that should replace SourceMod sending 1 query per ranked player. It works! However, the query takes over 50 seconds on my database with 10k~ users and 25k~ times, it's definitely not acceptable..
Does anyone have an idea for how this can be optimized? Obviously `JOIN`ing 2 times per iteration isn't the proper thing to do, but I can't figure out a better solution.. 
```sql
DROP PROCEDURE IF EXISTS UpdateAllPoints;
DELIMITER ;;
CREATE PROCEDURE UpdateAllPoints()
BEGIN
	DECLARE authid VARCHAR(32);
	DECLARE done INT DEFAULT 0;
	DECLARE cur CURSOR FOR (SELECT auth FROM playertimes WHERE points > 0.0 GROUP BY auth);
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
	OPEN cur;
	ranks: LOOP
		FETCH cur INTO authid;
		IF done THEN
			LEAVE ranks;
		END IF;
		UPDATE users u JOIN (SELECT SUM((points * (@f := 0.975 * @f) / 0.975)) total FROM playertimes t
				CROSS JOIN (SELECT @f := 1.0) params WHERE points > 0.0 AND auth = authid ORDER BY points DESC) temp
				SET u.points = temp.total WHERE auth = authid;
	END LOOP;
	CLOSE cur;
END;;
DELIMITER ;
CALL UpdateAllPoints();
```

**Comment by shavitush** [comment]
Well.. using the procedure above, I decided to do some optimization with indexes/data types in my server's database. By doing that, I cut the execution time from 58.656 seconds to 5.750!

    Before: /* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 3 queries: 58.656 sec. */
    After: /* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 3 queries: 5.750 sec. */

I believe it can be optimized even further, but I'm not an SQL expert unfortunately so it's hard on me. I'll push a commit that adds the indexes and changes `VARCHAR` to `CHAR(n)` in the database. You'll have to do those changes on your own to your existing database in order to benefit from better performance.

**Comment by strafe** [comment]
Are you happy to merge this now @shavitush or still wanting to optimise it further?

**Comment by shavitush** [comment]
I'll implement the procedure into the code itself, and then I'll merge this pull request. Then I'll work on the other things in this to-do in another pull request.

**Pull request merged**
