### PR TITLE
Translation fixes - (#318)

### PR DESCRIPTION
**Pull request by Technoblazed**

### CODE REVIEW

**Comment by shavitush** [comment]
is this ready for merge?

**Comment by Technoblazed** [comment]
I fixed the stuff that was actually broken so I guess so?

**Comment by Nickelony** [comment]
Have you fixed this extra (Tab) before "Best" aswell?

**Comment by Technoblazed** [comment]
Pretty sure that was in shavit's PR

**Comment by shavitush** [comment]
nope, but i'll handle it soon :)

**Pull request merged**
