### PR TITLE
add persist checkpoint data

### PR DESCRIPTION
**Pull request by Nairdaa**
As always and forever, deadwinter is a pogchamp.

https://github.com/shavitush/bhoptimer/issues/793

### CODE REVIEW

**Comment by Nairdaa** [comment]
TODO:

shavit_misc_persistcpdata 1/0 
Soon™

**Comment by kidfearless** [comment]
It looks like you started from an older commit and didn't update. As well as changed 2 other sections that aren't related to the intent of the PR. As it is now I'm reworking the PersistData section of the timer as it turns out cloning big arraylists causes some server lag. And adding checkpoint cloning on top of that definitely won't help.
```
Shavit_GetReplayData 82.362083(0.001060/0.001287)
props 1.010100(0.000012/0.001287)
snapshot 0.155400(0.000001/0.001287)
ClassNames 0.233100(0.000003/0.001287)
push 0.077700(0.000000/0.001287)
```

**Comment by Nairdaa** [comment]
"This branch has no conflicts with the base branch"

**Comment by deadw1nter** [comment]
> And adding checkpoint cloning on top of that definitely won't help.
If I don't clone the checkpoint array, it will not pass the array to aData.aCheckpoints. I don't really know how to avoid cloning array.

**Comment by kidfearless** [comment]
you shouldn't need to clone it [here](https://github.com/shavitush/bhoptimer/pull/952/files#diff-1dd7198ac08ba95c7cc87cf4c8816466R1292). At that point the arraylist has already been cloned once and is being cloned again. You should just simply assign it to the variable.

I can't accept this pr for now, as it's going to more than likely end up conflicting with the changes I'm currently working on. 

For it to be accepted in the future though, you'll need to set up shavit-misc to not delete the checkpoint(s) that will persist when the client leaves. Instead add them to the list of persistent checkpoints and null the players checkpoint variables. This will save their checkpoint(s) without having to clone them. 
On top of that you'll need to remove those changes that aren't part of the pr.

**Pull request closed without merging**
