### PR TITLE
add Shavit_GetTimesTeleported()

### PR DESCRIPTION
**Pull request by rtldg**
Untested so far but probably fine, right? Intended to be used by another plugin but maybe the teleport count could be added to the db eventually?

### CODE REVIEW

**Review by Nairdaa — COMMENTED** [review]
Most of people while segmenting/TAS teleport back to the same checkpoint several times at once (like 6-7 times before actually continuing). I don't see how storing this by the timer itself should be a thing. Waste of memory imo.

Prove me wrong.

**Comment by rtldg** [comment]
> Most of people while segmenting/TAS teleport back to the same checkpoint several times at once (like 6-7 times before actually continuing). 

intended for kz times

> I don't see how storing this by the timer itself should be a thing. 

easier

> Waste of memory imo.

not a lot. also don't you use python in your timer?

**Comment by Nairdaa** [comment]
> not a lot. also don't you use python in your timer?

Shut up, bitch XD, it was easily 3-4 years ago. There is no python at all on any servers I maintain and "my timer" is not even a thing anymore.

**Comment by kidfearless** [comment]
Could be used in the future for pro / tp kz runs

**Comment by Nairdaa** [comment]
> Could be used in the future for pro / tp kz runs

yea and as for now its just a useless waste of memory

**Comment by blankbhop** [comment]
can also be used for a sort of limiter to spamming cp's so people dont start teleporting to 50 cp's in one second

**Comment by hermansimensen** [comment]
0.0002 more megabytes of memory used... how will my server survive this?

**Pull request merged**
