### PR TITLE
no wr sound fix

### PR DESCRIPTION
**Pull request by Nairdaa**
after being blind for 2 days I finally noticed the SHITTY FUCKING mistake that KiD did

Fixed, works.

### CODE REVIEW

**Comment by Uronic** [comment]
idk lets keep commenting guys

**Review by shavitush — APPROVED** [review]
I'm sitting on the toilet right now reading your commit. I think it looks good)))))

**Comment by cytrus224** [comment]
If Kid reads this, he needs to merge this immediately

**Comment by Nairdaa** [comment]
I agree

pon., 24 sie 2020, 15:34 użytkownik cytrus224 <notifications@github.com>
napisał:

**Pull request closed without merging**
