### PR TITLE
Add styles configuration and deprecate shavit.inc configuration for styles

### PR DESCRIPTION
**Pull request by shavitush**
Will leave this pull request open for like 1-2 hours before I merge, looking for people to test. I tried myself and everything was backwards compatible and had 0 issues.

Edit styles in `addons/sourcemod/configs/shavit-styles.cfg`

### CODE REVIEW

**Comment by Technoblazed** [comment]
I'll give it a go

**Comment by Technoblazed** [comment]
I presume if you dont include the value, it defaults to default/0 ye?

**Comment by Technoblazed** [comment]
Out of curiosity, what can using turn binds for be abused by in bhop to require a config option?

**Comment by shavitush** [comment]
Default is 0 yeah, it says in the config file's header.  
Block moveleft is necessary for styles like W-Only because they only allow one key.  
I'll add a +left/right block setting too as 'legit servers' don't like them.

**Comment by Technoblazed** [comment]
The header just says to start with 0, doesn't say what happens if you don't include the values in the style settings

**Comment by shavitush** [comment]
```
// Start from 0 and increment every time. 0 is the default style.
```

**Comment by Technoblazed** [comment]
Yeah, I got that, I think we're misunderstanding each other ;-;

**Comment by Technoblazed** [comment]
I get 0 is the default, but in the actual styles itself, if you don't put a value in

**Comment by shavitush** [comment]
It shouldn't cause a problem, but I'd really prefer that it would happen

**Comment by shavitush** [comment]
Merged for now. Will also add some new features to this branch like the chat configuration file soon

**Pull request merged**
