### PR TITLE
Add new zone types to hookzone menu

### PR DESCRIPTION
**Pull request by Awesomerly**
This adds more recent zone types to the hookzone menu.

### CODE REVIEW

**Comment by Nairdaa** [comment]
The fuck?

**Comment by Awesomerly** [comment]
Yeap

**Comment by Awesomerly** [comment]
Wym by that? Is it the CI or something else

**Comment by Nairdaa** [comment]
This has to be a drunken halloween meme.

**Comment by Awesomerly** [comment]
Again, can you explain to me what you mean?

**Comment by rtldg** [comment]
I've got no clue either.

SM 1.12 build breaking but for other reasons so #mergeit!

**Pull request merged**
