### PR TITLE
Update shavit-rankings.sp

### PR DESCRIPTION
**Pull request by Nairdaa**
escape the map string properly

### CODE REVIEW

**Comment by Nairdaa** [comment]
No idea if this will finally fix the points/ranking counter. Haven't tested.

**Comment by Nairdaa** [comment]
It fixes the points at the server start, but still doesn't fix the !top command and the mapsdone in !stats.

Idk.

**Comment by rtldg** [comment]
>No idea if this will finally fix the points/ranking counter. Haven't tested.

>It fixes the points at the server start, but still doesn't fix the !top command and the mapsdone in !stats.

If that's the problem then check if it's fine after putting on this https://github.com/shavitush/bhoptimer/commit/7fb0f45c2c75714b4192f48e4b7ea030b0f9b5a9 and also running `sm_recalcall` on the server

**Comment by Nairdaa** [comment]
> > No idea if this will finally fix the points/ranking counter. Haven't tested.
> 
> > It fixes the points at the server start, but still doesn't fix the !top command and the mapsdone in !stats.
> 
> If that's the problem then check if it's fine after putting on this [7fb0f45](https://github.com/shavitush/bhoptimer/commit/7fb0f45c2c75714b4192f48e4b7ea030b0f9b5a9) and also running `sm_recalcall` on the server

I already have. Ive compiled all the newest files. Still buggy.

**Comment by rtldg** [comment]
This PR doesn't fix anything.

**Pull request closed without merging**
