### PR TITLE
imagine hitboxes

### PR DESCRIPTION
**Pull request by Nairdaa**
rumour is a beast by showing the hitboxes and mev is even beasterest for catching this fuck up

### CODE REVIEW

**Comment by kidfearless** [comment]
What's this for

**Comment by Nairdaa** [comment]
https://i.imgur.com/BUuo5Il.jpg
very bad



https://i.imgur.com/a2quJSV.png
very good


start the timer when your hitbox has actually left the zone, same shit applies for endzones

**Comment by OSCAR-WOS** [comment]
this gathered so much stipulation due to users requesting the timer start when your eye (camera) leaves the start zone, rather than your body. this change would invalidate all records also.

**Comment by Nairdaa** [comment]
> 
> 
> this gathered so much stipulation due to users requesting the timer start when your eye (camera) leaves the start zone, rather than your body. this change would invalidate all records also.

Yea better rely on something people established 10 years ago when they had no idea how the shit works and let's keep on having the bhoptimers counting the actual time wrong rather than having it done right. 

Following that logic, every timer with checkpoints should also stop counting the last checkpoint and start counting next at the same time the player's hitbox in the middle of the checkpoint line.

**Comment by Nairdaa** [comment]
Allowing people to drop all their weapons for 260 walk speed also invalidated all the strafe map records.

**Comment by OSCAR-WOS** [comment]
I hope you never receive modify access to this project

**Comment by Nairdaa** [comment]
Quite unfortunate for you I already have a green light from this timer's dev to implement this as an optional config and I'll do it wether you like it or not. That's the way the timers should be counted, right when you leave the startzone and right when you touch the endzone.

Let me quote rumour on this one:
[https://www.justhorseracing.com.au/wp-content/uploads/bendigophoto-734x460.jpg](url)


also

> I hope you never receive modify access to this project

lmao, you are so mad

**Comment by kidfearless** [comment]
> 
> 
> I hope you never receive modify access to this project

Can confirm Nairda's not getting modify access to the project XD.

In all honesty, I don't see many people implementing it on their servers, and most haven't. It's already been in the timer for years now in the form of `shavit_zones_offset`. If they really wanted zones to function that way they could always have modified that convar to match how they feel the zones should be.

The implementation as a convar is for people like Nairda who only thought about it the past week and found that they don't like it and want to change all their zones to match that method without querying their database.

As a side note, the defaults will be the same as before. I don't think many people will enjoy getting plummeted to the ground because they thought they were out of the start zone but their butts were still inside and therefore haven't fully left the start zone.

**Pull request closed without merging**
