### PR TITLE
reduce csgo hud size

### PR DESCRIPTION
**Pull request by Nairdaa**
its too big and looks shit on bigger resolutions

### CODE REVIEW

**Comment by blankbhop** [comment]
Why have it hard coded to begin with, could possibly make it a cvar where server owners can scale the hud to whatever they choose.

**Comment by rtldg** [comment]
why have it hardcoded or as a cvar to begin with, could possibly make it a client setting where clients can scale the hud to whatever they choose.

**Comment by Nairdaa** [comment]
> why have it hardcoded or as a cvar to begin with, could possibly make it a client setting where clients can scale the hud to whatever they choose.

Probably the best idea, but idk how well that would work. I also plan on completely reworking the CSGO hud, because the current one looks dogshit.

**Comment by rtldg** [comment]
> > why have it hardcoded or as a cvar to begin with, could possibly make it a client setting where clients can scale the hud to whatever they choose.
> 
> Probably the best idea, but idk how well that would work. I also plan on completely reworking the CSGO hud, because the current one looks dogshit.

Something like adding an `increase hud size` and `decrease hud size` menu options to the !hud menu which are saved in a cookie is probably a good way to do it. I'll probably test this out in a few hours

**Comment by Nairdaa** [comment]
Those few hours sure take you longer than expected :P

**Comment by rtldg** [comment]
> 
> 
> Those few hours sure take you longer than expected :P

any minute now, surely

**Comment by rtldg** [comment]
actually, I was testing but changing the font size does affect the alignment so I was messing with that and potentially not centering stuff and then I got annoyed that the $ symbol was in the hud so I looked into SFUI_ContractKillStart a lot and couldn't find out a way to do something about it

**Comment by Nairdaa** [comment]
Might or not rework the CSGO hud Soon™.

**Pull request closed without merging**
