### PR TITLE
Timerban

### PR DESCRIPTION
**Pull request by Nukoooo**
Implemented for nairda

### CODE REVIEW

**Comment by rtldg** [comment]
wondering if we should do anything in this pr for the blacklist style plugin. it might just break that plugin if merged as is.

**Comment by NukoOoOoOoO** [comment]
i blame nairda for requesting this. ask nairda @Nairdaa

**Comment by Nairdaa** [comment]
> wondering if we should do anything in this pr for the blacklist style plugin. it might just break that plugin if merged as is.

who cares about external plugins kek

**Comment by Nairdaa** [comment]
they should edit their plugin to something like "if timerbanned, do timer anyway" and voila

**Comment by Nairdaa** [comment]
Been over a year already 😢

**Comment by Nukoooo** [comment]
not needed and it can be done as a third-party plugin, closing!!!!!!!!

**Pull request closed without merging**
