### PR TITLE
Add teleport to !end

### PR DESCRIPTION
**Pull request by OfficialExtan**
Finally got it!

### CODE REVIEW

**Comment by shavitush** [comment]
Did you test it and made sure it doesn't cause issues if you teleport to the end, from the start zone?

**Comment by OfficialExtan** [comment]
Sure tested it a week before and still running fine on my server and without any issues :)

**Comment by shavitush** [comment]
:+1:

**Comment by OfficialExtan** [comment]
The next pull requests I will add are also all tested and working fine ;)

**Pull request merged**
