### PR TITLE
Add bhop_nux to mapfixes

### PR DESCRIPTION
**Pull request by BoomShotKapow**

### CODE REVIEW

**Comment by Nairdaa** [comment]
boomshot alive ;o

**Comment by BoomShotKapow** [comment]
> boomshot alive ;o

Shh....

**Comment by GAMMACASE** [comment]
What could be abused there via targetnames/classnames?

**Comment by BoomShotKapow** [comment]
> What could be abused there via targetnames/classnames?

To be honest, I just enabled it since the blocks were resetting every time you jumped on them. If there's a proper way to handle that, then I'll close this.

I'm also noticing it on: bhop_culture2

**Comment by GAMMACASE** [comment]
Do you use latest version of the timer? Doesn't seems to happen to me with changes done here https://github.com/shavitush/bhoptimer/pull/1123

**Comment by rtldg** [comment]
this seems to be solved by #1135 and https://github.com/hermansimensen/eventqueue-fix/pull/17 (or at least I don't encounter the reset-on-jump-on-block thing you mentioned with those prs and rngfix)

**Pull request closed without merging**
