### PR TITLE
add hud perf settings

### PR DESCRIPTION
**Pull request by Nairdaa**
added option to enable/disable perf ratio in hud from scroll styles

TODO later: 
- add an option to move perf ratio from right hud to main hud.

### CODE REVIEW

**Comment by shavitush** [comment]
it's ugly af bro

**Comment by Nairdaa** [comment]
> 
> 
> it's ugly af bro

no u

**Comment by Nairdaa** [comment]
When you implemented it you did it halfarsed and put it together with sync. What if I want to see the sync, but not perfs or vice versa?:<

**Comment by kidfearless** [comment]
No reason not to add it. Unless we run out of bitflags again.

**Pull request merged**
