### PR TITLE
only print the stage time message once per stage

### PR DESCRIPTION
**Pull request by rtldg**

### CODE REVIEW

**Comment by kidfearless** [comment]
This was intentional so that players running segmented could see their time difference while grinding. With the current change a checkpointing player would need to restart his run every time he goes through the stage zone.

**Comment by rtldg** [comment]
What about making it print every time for segmented then? (And TAS whenever hypnos decides that is ready to merge)

**Comment by Nairdaa** [comment]
> What about making it print every time for segmented then? (And TAS whenever hypnos decides that is ready to merge)

That would be the best idea.

**Comment by kidfearless** [comment]
The best thing to do would be to save their last stage for every checkpoint saved, and then reset it to the saved value when they teleport.

**Comment by Nairdaa** [comment]
> The best thing to do would be to save their last stage for every checkpoint saved, and then reset it to the saved value when they teleport.

No need to store even more data in the array. What rtldg suggested is just an if statement and to me seems to be the best solution.

**Pull request merged**
