### PR TITLE
Update replay-stocks.sp

### PR DESCRIPTION
**Pull request by Nairdaa**
fix logic behind testing if it works or not and when to actually throw an error

### CODE REVIEW

**Comment by rtldg** [comment]
If `OpenFile` failed then `fTest` would be `null` and `CloseHandle(null)` is okay to do so there's not actually anything broken here although the logic isn't that clear

**Comment by Nairdaa** [comment]
Closing a handle should only be done if it was validly opened. Calling CloseHandle on null may not cause a crash, but it leads to unnecessary function calls. 

The "updated code" fixes the "issue" by ensuring that it checks if the file was successfully opened before attempting to close it.

**Comment by Nairdaa** [comment]
If you spam enough it leads to this: 
image
Can't do anything about ANY of the running replays now, untill this run is finished. Ignore the "unknown" in the name, that's just because it's an old replay and it's missing the player's name in it's data.

**Review by kidfearless — APPROVED** [review]
Looks good, merge it

**Pull request merged**
