### PR TITLE
Add CI.

### PR DESCRIPTION
**Pull request by fuckOff1703**

### CODE REVIEW

**Comment by rtldg** [comment]
I'll check/test this to merge in a little bit

**Comment by rtldg** [comment]
Most likely as long as it doesn't steal all of shavit's free github action minutes

**Comment by fuckOff1703** [comment]
Public repo don't have limits.
https://github.com/features/actions
> We love open source © GitHub

**Comment by rtldg** [comment]
Ah didn't know that, thanks for letting me go

**Comment by rtldg** [comment]
know

**Comment by rtldg** [comment]
I removed the ripext & sm-json includes because I really don't like either of them & I want to replace them eventually. It wgets & extracts the dependencies now (including eventqueuefix)

**Comment by fuckOff1703** [comment]
> I removed the ripext & sm-json

`git revert 9a259c91907ebfe37fa02e24572e524cca086cc7`
I think this better, but anyway this merged.

**Pull request merged**
