### PR TITLE
useless pr, but KiD asked for it

### PR DESCRIPTION
**Pull request by Nairdaa**
added braces

### CODE REVIEW

**Comment by hermansimensen** [comment]
You are missing a new line at the end of the file. This will break everything

**Comment by kidfearless** [comment]
> 
> 
> You are missing a new line at the end of the file. This will break everything

This will ruin the code base!!!11!!12

**Review by sneak-it — APPROVED** [review]
It's ok I think

**Comment by Nairdaa** [comment]
fixed the code

**Comment by sneak-it** [comment]
How do I revoke my approval 😡

**Pull request merged**
