### PR TITLE
Translation fixes for other langs

### PR DESCRIPTION
**Pull request by Technoblazed**
- 1 pleb mistake
- A few multi-language changes.

### CODE REVIEW

**Comment by Technoblazed** [comment]
@nickelony Can you confirm this was everything please?

**Comment by Nickelony** [comment]
I'm an idiot.

**Comment by Nickelony** [comment]
I've tested everything and I can't find any issues except there is a TAB too much before BEST.

**Comment by Technoblazed** [comment]
I'm gonna delete the pr and resubmit

**Comment by Technoblazed** [comment]
I don't want 50 commit or whatever it is in one pr

**Comment by shavitush** [comment]
you could just squash it all into a single one!

**Comment by shavitush** [comment]
Actually I'll just merge it like that because it doesn't really matter

**Comment by Technoblazed** [comment]
INSANE

**Pull request merged**
